### PR TITLE
Bash compatibility and method to skip secondary disks

### PR DESCRIPTION
**Pull request by luizoti**
Overall I didn't add any fancy functions, so I tested everything is working, but if you're willing to test again and notice something wrong I can change it, to deal with the problem of formatting the wrong disk, I added an array of disks and had it checked whether or not they are sda, I was wondering if the board_name variable was affected and also includes tl-wdr4300.

OBS: NOTE: It includes some configuration files for convenience, the ideal is that the user deletes it when he does not want to use it.

Exactly because it has some specific changes that are useful for my use, I wouldn't go up a PR, but this last change in relation to disks can be useful.

### CODE REVIEW

**Comment by attila-lendvai** [comment]
thanks for the PR!

so, to clarify: most of these commits are not interesting for the general public and shouldn't be merged, except the bash related changes, and the last commit, right?

**Comment by luizoti** [comment]
Yes, the ones related to bash, syntax changes and the last one the others, are completely optional.

**Comment by attila-lendvai** [comment]
i'll reopen this until i get to merging the interesting parts. (unless you are preparing a PR that is ready to merge as is)

**Comment by attila-lendvai** [comment]
i have adapted some of this PR.

thanks!

**Pull request closed without merging**
