### PR TITLE
URL doesn't work for Dlink-DIR885l

### PR DESCRIPTION
**Pull request by vthg2themax**
https://downloads.openwrt.org/releases/17.01.4/targets/bcm53xx/generic/lede-imagebuilder-17.01.4-bcm53xx.Linux-x86_64.tar.xz
Is the URL I needed to setup my D-Link Dir-885L.
Not sure if that breaks other architectures, but it was needed for my situation. Thanks again for this great idea by the way!

### CODE REVIEW

**Comment by attila-lendvai** [comment]
thanks, i'll have to investigate/test it. it probably breaks the others.

i'm glad you found it useful!

**Comment by attila-lendvai** [comment]
@vthg2themax can you please paste here the ./build.sh command line that you used? i'll add it to the readme... i guess you specified "" as variant (second arg), right?

**Comment by vthg2themax** [comment]
Here's the Build Command I used: 
./build.sh bcm53xx generic dlink-dir-885l
and here's the result:

root@vince-virtual-machine:/home/vince/Desktop/openwrt-auto-extroot-master# ./build.sh bcm53xx generic dlink-dir-885l
/home/vince/Desktop/openwrt-auto-extroot-master/build /home/vince/Desktop/openwrt-auto-extroot-master
--2018-07-12 16:30:43--  https://downloads.openwrt.org/releases/17.01.4/targets/bcm53xx/generic/lede-imagebuilder-17.01.4-bcm53xx-generic.Linux-x86_64.tar.xz
Resolving downloads.openwrt.org (downloads.openwrt.org)... 148.251.78.235, 2a01:4f8:202:43ea::2
Connecting to downloads.openwrt.org (downloads.openwrt.org)|148.251.78.235|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.openwrt.org/releases/17.01.4/targets/bcm53xx/generic/openwrt-imagebuilder-17.01.4-bcm53xx-generic.Linux-x86_64.tar.xz [following]
--2018-07-12 16:30:44--  https://downloads.openwrt.org/releases/17.01.4/targets/bcm53xx/generic/openwrt-imagebuilder-17.01.4-bcm53xx-generic.Linux-x86_64.tar.xz
Reusing existing connection to downloads.openwrt.org:443.
HTTP request sent, awaiting response... 404 Not Found
2018-07-12 16:30:44 ERROR 404: Not Found.

**Comment by attila-lendvai** [comment]
thanks!

i've reported [a feature request](https://bugs.openwrt.org/index.php?do=details&task_id=1670) to openwrt to make the imagebuilder URL easily predictable.

until then some targets will not work out of the box without adding much extra complexity to the `build.sh` script. users need to delete the `${TARGET_VARIANT}` by hand from the file name (but not the path).

**Comment by vthg2themax** [comment]
So are you up for some conditional logic for patching things, (I would be willing to muck up the code to make this easier for people to pull and use), or did you just want to leave things as they are?

**Comment by attila-lendvai** [comment]
i'd fancy to keep that script simple, but i don't mind including the extra complexity if someone else cuts through the jungle until the openwrt people do something about it.

although, we all know that god kills a kitten every time a shell script grows beyond a page... :)

jokes aside, i won't reject that PR if you work it out.

**Comment by attila-lendvai** [comment]
FTR, meanwhile this has been fixed upstream.

**Pull request closed without merging**
